
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Si = 3;
  public static final int Parentesis_c = 13;
  public static final int Parentesis_a = 12;
  public static final int Suma = 7;
  public static final int Numero = 18;
  public static final int Entero = 2;
  public static final int ERROR = 19;
  public static final int Mientras = 5;
  public static final int Identificador = 17;
  public static final int Llave_c = 15;
  public static final int Llave_a = 14;
  public static final int Programa = 16;
  public static final int Sino = 4;
  public static final int EOF = 0;
  public static final int Division = 10;
  public static final int Resta = 8;
  public static final int error = 1;
  public static final int Asignacion = 11;
  public static final int Igual = 6;
  public static final int Multiplicacion = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Entero",
  "Si",
  "Sino",
  "Mientras",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Asignacion",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "Programa",
  "Identificador",
  "Numero",
  "ERROR"
  };
}

