
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 06 14:08:58 CEST 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Entero = 9;
  public static final int Llave_c = 8;
  public static final int Llave_a = 7;
  public static final int Negacion_logica = 31;
  public static final int Y_logico = 29;
  public static final int Menor = 23;
  public static final int Asignacion = 17;
  public static final int Corchete_c = 4;
  public static final int Corchete_a = 3;
  public static final int Mayor = 25;
  public static final int Que = 16;
  public static final int Para = 13;
  public static final int O_logico = 30;
  public static final int Division = 21;
  public static final int Parentesis_c = 6;
  public static final int Modulo = 22;
  public static final int Parentesis_a = 5;
  public static final int EOF = 0;
  public static final int Logico = 10;
  public static final int error = 1;
  public static final int Mayor_igual = 26;
  public static final int Linea = 32;
  public static final int Programa = 2;
  public static final int Repita = 14;
  public static final int ERROR = 36;
  public static final int Menor_igual = 24;
  public static final int Diferencia = 28;
  public static final int Identificador = 33;
  public static final int Si = 11;
  public static final int Punto_coma = 34;
  public static final int Resta = 19;
  public static final int Sino = 12;
  public static final int Multiplicacion = 20;
  public static final int Numero = 35;
  public static final int Hasta = 15;
  public static final int Suma = 18;
  public static final int Igual = 27;
}

