
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 05 12:42:11 CEST 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Entero = 9;
  public static final int Llave_c = 8;
  public static final int Llave_a = 7;
  public static final int Negacion_logica = 35;
  public static final int MirarAbajo = 14;
  public static final int Y_logico = 33;
  public static final int Menor = 27;
  public static final int Asignacion = 21;
  public static final int Corchete_c = 4;
  public static final int Corchete_a = 3;
  public static final int Mayor = 29;
  public static final int Para = 19;
  public static final int MirarDerecha = 16;
  public static final int MirarIzquierda = 15;
  public static final int O_logico = 34;
  public static final int Division = 25;
  public static final int Parentesis_c = 6;
  public static final int Modulo = 26;
  public static final int Parentesis_a = 5;
  public static final int EOF = 0;
  public static final int Logico = 10;
  public static final int error = 1;
  public static final int Mayor_igual = 30;
  public static final int Vector = 11;
  public static final int Linea = 36;
  public static final int Programa = 2;
  public static final int Repita = 20;
  public static final int ERROR = 39;
  public static final int Menor_igual = 28;
  public static final int Diferencia = 32;
  public static final int Avanzar = 12;
  public static final int Identificador = 37;
  public static final int Si = 17;
  public static final int Resta = 23;
  public static final int MirarArriba = 13;
  public static final int Sino = 18;
  public static final int Multiplicacion = 24;
  public static final int Numero = 38;
  public static final int Suma = 22;
  public static final int Igual = 31;
}

