
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 05 11:25:07 CEST 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Si = 3;
  public static final int Parentesis_c = 12;
  public static final int Parentesis_a = 11;
  public static final int Suma = 7;
  public static final int Numero = 17;
  public static final int Entero = 2;
  public static final int ERROR = 19;
  public static final int Mientras = 5;
  public static final int Identificador = 16;
  public static final int Llave_c = 14;
  public static final int Llave_a = 13;
  public static final int Programa = 15;
  public static final int Sino = 4;
  public static final int EOF = 0;
  public static final int Division = 10;
  public static final int Resta = 8;
  public static final int error = 1;
  public static final int Asignacion = 18;
  public static final int Igual = 6;
  public static final int Multiplicacion = 9;
}

